name: websec build-n-ship

on:
  push:
    branches:
      - master

jobs:
  build-n-ship:
    name: Build & Ship Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        ref: master
        with:
        fetch-depth: 2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to HCR
        run: |
          docker login --username=_ --password=${{ secrets.HTOK }} registry.heroku.com
      - name: Build Docker image & add Heroku tag
        run: |
          docker buildx build --platform linux/amd64 -t registry.heroku.com/${{ secrets.HAPPNAME }}/web
      - name: Push Docker image to HCR
        run: |
          docker push registry.heroku.com/${{ secrets.HAPPNAME }}/web
      - name: Deploy new image on Heroku app
        run: |
          heroku container:release web --app ${{ secrets.HAPPNAME }}