on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=mngf87
            -Dsonar.projectKey=Mngf87_vulnerable-web-app

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: 'imgcheck'

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'imgcheck'
          format: 'sarif'
          output: 'trivy-results.sarif'
                 
      - name: Build and push Docker image to Heroku
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: registry.heroku.com/${{ secrets.HAPPNAME }}/web
          provenance: false
          no-cashe: true
          platforms: linux/amd64

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HTOK }}
        run: |
          heroku container:release web --app ${{ secrets.HAPPNAME }}
        
      - name: OWASP ZAP Scan
        uses: zaproxy/action-api-scan@v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          format: openapi
          target: 'https://ekoparty-mgarciaferro-352282513fcb.herokuapp.com/'
          cmd_options: '-a'

      - name: Upload ZAP Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ZAP Report
          path: zap_report.html
